In [ ]:
import numpy as np

# create arrays using numpy
# create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape((1,5)) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [7]:
arr3 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr3)
arr3.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(0,10,2).reshape((5,1))

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [16]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of numpy array : 

arr = np.array([[1,2,3], [4,5,6]])
print(f'array : {arr}')
print(f'array shape : {arr.shape}')
print(f'array dimension : {arr.ndim}')
print(f'array size : {arr.size}')
print(f'data type : {arr.dtype}')
print(f'Data size : {arr.itemsize}')

array : [[1 2 3]
 [4 5 6]]
array shape : (2, 3)
array dimension : 2
array size : 6
data type : int64
Data size : 8


In [19]:
# Numpy vectorized operations : 

arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array([10,20,30,40,50])

# Element wise addition : 
print(f'Addition : {arr1 + arr2}')

Addition : [[11 22 33 44 55]]


In [20]:
# Element wise substraction : 
print(f'Substraction : {arr1 - arr2}')

Substraction : [[ -9 -18 -27 -36 -45]]


In [21]:
# Element wise multiplication : 
print(f'Multiplication : {arr1 * arr2}')

Multiplication : [[ 10  40  90 160 250]]


In [22]:
# Element wise division : 
print(f'Multiplication : {arr1 / arr2}')

Multiplication : [[0.1 0.1 0.1 0.1 0.1]]


In [25]:
# Universal Functions : 
arr = np.array([1,2,3,4,5,6])
# square root
print(f'square root: {np.sqrt(arr)}')
# exponential 
print(f'exponential : {np.exp(arr)}')

square root: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
exponential : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


In [26]:
# Sine 
print(f'Sine : {np.sin(arr)}')

Sine : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [27]:
# natural log
print(f'log : {np.log(arr)}')

log : [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [28]:
# array slicing and indexing : 
arr = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
print('Array : \n', arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [52]:
print(arr[1:, 2:])

[[ 7  8]
 [11 12]]


In [53]:
# Modify array elements : 
arr[0,0] = 100

In [54]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [55]:
arr[1:] = 100

In [56]:
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [ ]:
# Statistical concepts --> Normalization 
# we need to change the data to have a mean of 0 and std of 1
arr = np.array([1,2,3,4,5])
mean = np.mean(arr)
std = np.std(arr)
print(f'mean : {np.mean(arr)}')
print(f'standard deviation : {np.std(arr)}')
# Normalize the data --> 
normalized_data = (arr - mean) / std
print(f'normalized data : {normalized_data}')

mean : 3.0


In [69]:
data = np.arange(1,11)

# mean
mean = np.mean(data)
print(f'mean : {mean}')

# median
median = np.median(data)
print(f'meadian : {median}')

# standard variation
std = np.std(data)
print(f'standard deviation : {std}')

# variance
var = np.var(data)
print(f'var : {var}')

mean : 5.5
meadian : 5.5
standard deviation : 2.8722813232690143
var : 8.25


In [71]:
# logical operations : 
data = np.arange(1,11)

data[(data>5) & (data<8)]

array([6, 7])